export const SET_PRO_CENTER = 'SET_PRO_CENTER'

export const SET_PROJECTS = 'SET_PROJECTS'

export const SET_KNOWLEDGES = 'SET_KNOWLEDGES'

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT'

export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'

export const SET_CURRENT_KNOWLEDGE = 'SET_CURRENT_KNOWLEDGE'


